language: android
  
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
      - 'intel-android-extra-license.+'
      - '.+'
jdk:
  - oraclejdk8
